config/routes.rb
Rails.application.routes.draw do
  resources :interns
  root 'interns#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/intern.rb
class Intern < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/interns_controller.rb
class InternsController < ApplicationController
  before_action :set_intern, only: %i[ show edit update destroy ]

  # GET /interns or /interns.json
  def index
    @interns = Intern.all
  end

  # GET /interns/1 or /interns/1.json
  def show
  end

  # GET /interns/new
  def new
    @intern = Intern.new
  end

  # GET /interns/1/edit
  def edit
  end

  # POST /interns or /interns.json
  def create
    @intern = Intern.new(intern_params)

    respond_to do |format|
      if @intern.save
        format.html { redirect_to intern_url(@intern), notice: "Intern was successfully created." }
        format.json { render :show, status: :created, location: @intern }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @intern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interns/1 or /interns/1.json
  def update
    respond_to do |format|
      if @intern.update(intern_params)
        format.html { redirect_to intern_url(@intern), notice: "Intern was successfully updated." }
        format.json { render :show, status: :ok, location: @intern }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @intern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interns/1 or /interns/1.json
  def destroy
    @intern.destroy!

    respond_to do |format|
      format.html { redirect_to interns_url, notice: "Intern was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intern
      @intern = Intern.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intern_params
      params.require(:intern).permit(:index, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interns_helper.rb
module InternsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">

    <%= link_to 'Intern Assignment', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

     

      </ul>

    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/interns/_form.html.erb
<%= form_with(model: intern) do |form| %>
  <% if intern.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intern.errors.count, "error") %> prohibited this intern from being saved:</h2>

      <ul>
        <% intern.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :index%>
    <%= form.text_field :index, class:"form-control", placeholder:"Index number" %>
  </div>

  <div class="field form-group">
    <%= form.label :value %>
    <%= form.number_field :value, class:"form-control", placeholder:"Value" %>
  </div>
<br/>
  <div class="actions">
    <%= form.submit 'Update Index', class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/interns/edit.html.erb
<h1>Editting Index</h1>
<br/>
<%= render "form", intern: @intern %>

<br/>

  <%= link_to 'Back', interns_path, class: "btn btn-dark mr-2" %>
  <%= button_to "Destroy", @intern, method: :delete, class: "btn btn-danger" %>

app/views/interns/index.html.erb
<h1><center>Table 1</center></h1>
<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th><center>Index</center></th>
      <th><center>Value</center></th>
      <th colspan="2"><center>Action</center></th>
    </tr>
  </thead>

  <tbody>
  <% @interns.each do |intern| %>
    <tr>
      <td><%= intern.index %></td>
      <td><%= intern.value %></td>
      <td><%= link_to 'Show', intern %></td>
      <td><%= link_to 'Edit', edit_intern_path(intern) %></td>
    </tr>
  <% end %>
</tbody>

</table>

<br/>

<%= link_to 'New Index', new_intern_path, class:"btn btn-primary"  %>

<br/>
<br/>
<br/>
<br/>

<h1><center>Table 2</center></h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th><center>Category</center></th>
      <th><center>Value</center></th>
    </tr>
  </thead>

  <tbody>

    <tr>
      <td>Alpha</td>
      <td><%= @interns.where(index: 'A5').sum(:value) + @interns.where(index: 'A20').sum(:value) %></td>
    </tr>
    <tr>
      <td>Beta</td>
      <td><%= @interns.where(index: 'A15').sum(:value) / @interns.where(index: 'A7').sum(:value) %></td>
    </tr>
    <tr>
      <td>Charlie</td>
      <td><%= @interns.where(index: 'A13').sum(:value) * @interns.where(index: 'A12').sum(:value) %></td>
    </tr>

</tbody>

</table>

<br/>
<br/>

app/views/interns/new.html.erb
<h1>Add New index</h1>
<br/>
<%= render 'form', intern: @intern %>

<br/>
<%= link_to 'Back', interns_path, class:"btn btn-dark" %>

app/views/interns/show.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Index</th>
      <th>Value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @intern.index %></td>
      <td><%= @intern.value %></td>
    </tr>
  </tbody>
</table>

  <br/>

  <%= link_to 'Edit', edit_intern_path(@intern), class:"btn btn-secondary" %>

<%= link_to 'Back', interns_path, class:"btn btn-dark" %>
<br/><br/>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Assignment</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">

      <br/>
      <% if notice %>
      <%= render 'layouts/alert' %>
      <% end %>


      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>